language: node_js
node_js:
  - "8"
install:
  - yarn
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - npm build
  # - yarn danger
after_success:
  - npm run report-coverage
  - npm run semantic-release;
  - echo 'Success, your PR is awaesome :o'

after_failure:
    - echo 'Failure, oh shit, sorry but your PR need a review'
